##
####
##
version: 2
updates:
  # Keep package.json (& lockfiles) up to date as soon as
  # new versions are published to the npm registry
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  # Keep Dockerfile up to date, batching pull requests weekly
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
