version: 3
server: https://app.fossa.com

project:
  id: "addonfactory-ucc-generator"
  team: "TA-Automation"

targets:
  exclude:
    - type: setuptools
      path: splunk_add_on_ucc_framework/commands/init_template/{{cookiecutter.addon_name}}/package/lib
    - type: setuptools
      path: tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/lib
    - type: setuptools
      path: tests/testdata/test_addons/package_global_config_configuration/package/lib
    - type: setuptools
      path: tests/testdata/test_addons/package_global_config_everything/package/lib
