# link to all config options https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# MD001/heading-increment
MD001: false

# MD010/no-hard-tabs
MD010:
  # Include code blocks
  code_blocks: false

# MD013/line-length
MD013: false

# MD024/no-duplicate-heading
MD024: false

# MD025/single-title/single-h1
MD025: false

# MD028/no-blanks-blockquote
MD028: false

# MD033/no-inline-html
MD033: false

# MD034/no-bare-urls
MD034: false

# MD040/fenced-code-language
MD040: false

# MD041/first-line-heading/first-line-h1
MD041: false

# MD046/code-block-style
MD046: false
