---
excludes:
  paths:
    - pattern: "docs/**"
      reason: "DOCUMENTATION_OF"
      comment: "The files are only used for documentation. Not included in released artifacts."
    - pattern: "tests/**"
      reason: "TEST_OF"
      comment: "Directory is only used for testing. Not included in released artifacts."