# SPDX-FileCopyrightText: 2020 Splunk Inc.
#
# SPDX-License-Identifier: Apache-2.0

ARG SPLUNK_VERSION=latest
FROM splunk/splunk:$SPLUNK_VERSION
ARG SPLUNK_VERSION=latest
ARG SPLUNK_APP_ID=TA_UNKNOWN
ARG SPLUNK_APP_PACKAGE=output
RUN echo Splunk VERSION=$SPLUNK_VERSION

COPY deps/apps /opt/splunk/etc/apps/

COPY output/Splunk_TA_UCCExample /opt/splunk/etc/apps/Splunk_TA_UCCExample
