import { HttpResponse, http } from 'msw';

export const ROW_DATA = [
    {
        name: 'aaaaaa',
        id: 'https://localhost:8000/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/aaaaaa',
        updated: '1970-01-01T00:00:00+00:00',
        links: {
            alternate:
                '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/aaaaaa',
            list: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/aaaaaa',
            edit: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/aaaaaa',
            remove: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/aaaaaa',
        },
        author: 'admin',
        acl: {
            app: 'Splunk_TA_UCCExample',
            can_change_perms: true,
            can_list: true,
            can_share_app: true,
            can_share_global: true,
            can_share_user: true,
            can_write: true,
            modifiable: true,
            owner: 'admin',
            perms: {
                read: ['*'],
                write: ['admin', 'sc_admin'],
            },
            removable: true,
            sharing: 'global',
        },
        content: {
            account_multiple_select: 'one',
            account_radio: '1',
            auth_type: 'basic',
            custom_endpoint: 'login.example.com',
            disabled: false,
            'eai:acl': null,
            'eai:appName': 'Splunk_TA_UCCExample',
            'eai:userName': 'nobody',
            password: '******',
            custom_text: 'a',
            token: '******',
            username: 'aaaaaa',
        },
    },
    {
        name: 'aaaaaaa',
        id: 'https://localhost:8000/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/aaaaaaa',
        updated: '1970-01-01T00:00:00+00:00',
        links: {
            alternate:
                '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/aaaaaaa',
            list: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/aaaaaaa',
            edit: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/aaaaaaa',
            remove: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/aaaaaaa',
        },
        author: 'admin',
        acl: {
            app: 'Splunk_TA_UCCExample',
            can_change_perms: true,
            can_list: true,
            can_share_app: true,
            can_share_global: true,
            can_share_user: true,
            can_write: true,
            modifiable: true,
            owner: 'admin',
            perms: {
                read: ['*'],
                write: ['admin', 'sc_admin'],
            },
            removable: true,
            sharing: 'global',
        },
        content: {
            account_multiple_select: 'one',
            account_radio: '1',
            auth_type: 'basic',
            custom_endpoint: 'login.example.com',
            disabled: false,
            'eai:acl': null,
            'eai:appName': 'Splunk_TA_UCCExample',
            'eai:userName': 'nobody',
            password: '******',
            custom_text: 'ab',
            token: '******',
            username: 'aaaaaaa',
        },
    },
    {
        name: 'bbbb',
        id: 'https://localhost:8000/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/bbbb',
        updated: '1970-01-01T00:00:00+00:00',
        links: {
            alternate: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/bbbb',
            list: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/bbbb',
            edit: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/bbbb',
            remove: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/bbbb',
        },
        author: 'admin',
        acl: {
            app: 'Splunk_TA_UCCExample',
            can_change_perms: true,
            can_list: true,
            can_share_app: true,
            can_share_global: true,
            can_share_user: true,
            can_write: true,
            modifiable: true,
            owner: 'admin',
            perms: {
                read: ['*'],
                write: ['admin', 'sc_admin'],
            },
            removable: true,
            sharing: 'global',
        },
        content: {
            account_multiple_select: 'one',
            account_radio: '1',
            auth_type: 'basic',
            custom_endpoint: 'login.example.com',
            disabled: false,
            'eai:acl': null,
            'eai:appName': 'Splunk_TA_UCCExample',
            'eai:userName': 'nobody',
            password: '******',
            custom_text: 'abc',
            token: '******',
            username: 'aaaaaa',
        },
    },
    {
        name: 'ccc',
        id: 'https://localhost:8000/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/ccc',
        updated: '1970-01-01T00:00:00+00:00',
        links: {
            alternate: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/ccc',
            list: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/ccc',
            edit: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/ccc',
            remove: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/ccc',
        },
        author: 'admin',
        acl: {
            app: 'Splunk_TA_UCCExample',
            can_change_perms: true,
            can_list: true,
            can_share_app: true,
            can_share_global: true,
            can_share_user: true,
            can_write: true,
            modifiable: true,
            owner: 'admin',
            perms: {
                read: ['*'],
                write: ['admin', 'sc_admin'],
            },
            removable: true,
            sharing: 'global',
        },
        content: {
            account_multiple_select: 'one',
            account_radio: '1',
            auth_type: 'basic',
            custom_endpoint: 'login.example.com',
            disabled: false,
            'eai:acl': null,
            'eai:appName': 'Splunk_TA_UCCExample',
            'eai:userName': 'nobody',
            password: '******',
            custom_text: 'abcd',
            token: '******',
            username: 'ccc',
        },
    },
    {
        name: 'ddddd',
        id: 'https://localhost:8000/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/ddddd',
        updated: '1970-01-01T00:00:00+00:00',
        links: {
            alternate: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/ddddd',
            list: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/ddddd',
            edit: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/ddddd',
            remove: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/ddddd',
        },
        author: 'admin',
        acl: {
            app: 'Splunk_TA_UCCExample',
            can_change_perms: true,
            can_list: true,
            can_share_app: true,
            can_share_global: true,
            can_share_user: true,
            can_write: true,
            modifiable: true,
            owner: 'admin',
            perms: {
                read: ['*'],
                write: ['admin', 'sc_admin'],
            },
            removable: true,
            sharing: 'global',
        },
        content: {
            account_multiple_select: 'two',
            account_radio: '1',
            auth_type: 'basic',
            custom_endpoint: 'login.example.com',
            disabled: false,
            'eai:acl': null,
            'eai:appName': 'Splunk_TA_UCCExample',
            'eai:userName': 'nobody',
            password: '******',
            custom_text: 'ab',
            token: '******',
            username: 'ddddd',
        },
    },
    {
        name: 'test1',
        id: 'https://localhost:8000/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/test1',
        updated: '1970-01-01T00:00:00+00:00',
        links: {
            alternate: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/test1',
            list: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/test1',
            edit: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/test1',
            remove: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/test1',
        },
        author: 'admin',
        acl: {
            app: 'Splunk_TA_UCCExample',
            can_change_perms: true,
            can_list: true,
            can_share_app: true,
            can_share_global: true,
            can_share_user: true,
            can_write: true,
            modifiable: true,
            owner: 'admin',
            perms: {
                read: ['*'],
                write: ['admin', 'sc_admin'],
            },
            removable: true,
            sharing: 'global',
        },
        content: {
            account_multiple_select: 'two',
            account_radio: '1',
            auth_type: 'basic',
            custom_endpoint: 'login.example.com',
            disabled: false,
            'eai:acl': null,
            'eai:appName': 'Splunk_TA_UCCExample',
            'eai:userName': 'nobody',
            password: '******',
            custom_text: 'aaaaa',
            token: '******',
            username: 'test1',
        },
    },
    {
        name: 'test2',
        id: 'https://localhost:8000/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/test2',
        updated: '1970-01-01T00:00:00+00:00',
        links: {
            alternate: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/test2',
            list: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/test2',
            edit: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/test2',
            remove: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/test2',
        },
        author: 'admin',
        acl: {
            app: 'Splunk_TA_UCCExample',
            can_change_perms: true,
            can_list: true,
            can_share_app: true,
            can_share_global: true,
            can_share_user: true,
            can_write: true,
            modifiable: true,
            owner: 'admin',
            perms: {
                read: ['*'],
                write: ['admin', 'sc_admin'],
            },
            removable: true,
            sharing: 'global',
        },
        content: {
            account_multiple_select: 'two',
            account_radio: '1',
            auth_type: 'basic',
            custom_endpoint: 'login.example.com',
            disabled: false,
            'eai:acl': null,
            'eai:appName': 'Splunk_TA_UCCExample',
            'eai:userName': 'nobody',
            password: '******',
            custom_text: 'two',
            token: '******',
            username: 'test1',
        },
    },
    {
        name: 'testsomethingelse',
        id: 'https://localhost:8000/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/testsomethingelse',
        updated: '1970-01-01T00:00:00+00:00',
        links: {
            alternate:
                '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/testsomethingelse',
            list: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/testsomethingelse',
            edit: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/testsomethingelse',
            remove: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/testsomethingelse',
        },
        author: 'admin',
        acl: {
            app: 'Splunk_TA_UCCExample',
            can_change_perms: true,
            can_list: true,
            can_share_app: true,
            can_share_global: true,
            can_share_user: true,
            can_write: true,
            modifiable: true,
            owner: 'admin',
            perms: {
                read: ['*'],
                write: ['admin', 'sc_admin'],
            },
            removable: true,
            sharing: 'global',
        },
        content: {
            account_multiple_select: 'two',
            account_radio: '1',
            auth_type: 'basic',
            custom_endpoint: 'login.example.com',
            disabled: false,
            'eai:acl': null,
            'eai:appName': 'Splunk_TA_UCCExample',
            'eai:userName': 'nobody',
            password: '******',
            custom_text: 'testsomethingelse',
            token: '******',
            username: 'test1',
        },
    },
    {
        name: 'zzzzzzz',
        id: 'https://localhost:8000/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/zzzzzzz',
        updated: '1970-01-01T00:00:00+00:00',
        links: {
            alternate:
                '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/zzzzzzz',
            list: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/zzzzzzz',
            edit: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/zzzzzzz',
            remove: '/servicesNS/nobody/Splunk_TA_UCCExample/splunk_ta_uccexample_account/zzzzzzz',
        },
        author: 'admin',
        acl: {
            app: 'Splunk_TA_UCCExample',
            can_change_perms: true,
            can_list: true,
            can_share_app: true,
            can_share_global: true,
            can_share_user: true,
            can_write: true,
            modifiable: true,
            owner: 'admin',
            perms: {
                read: ['*'],
                write: ['admin', 'sc_admin'],
            },
            removable: true,
            sharing: 'global',
        },
        content: {
            account_multiple_select: 'one',
            account_radio: '1',
            auth_type: 'basic',
            custom_endpoint: 'login.example.com',
            disabled: false,
            'eai:acl': null,
            'eai:appName': 'Splunk_TA_UCCExample',
            'eai:userName': 'nobody',
            password: '******',
            custom_text: '222222',
            token: '******',
            username: 'zzzzz',
        },
    },
];

export const MockRowData = {
    links: {
        create: `/servicesNS/nobody/-/splunk_ta_uccexample_account/_new`,
    },
    updated: '2023-08-21T11:54:12+00:00',
    entry: ROW_DATA,
    messages: [],
};

export const ServerHandlers = [
    http.get(`/servicesNS/nobody/-/splunk_ta_uccexample_account`, () =>
        HttpResponse.json(MockRowData)
    ),
    http.get('/servicesNS/nobody/-/splunk_ta_uccexample_example_input_one', () =>
        HttpResponse.json(MockRowData)
    ),
];
