name: "Get & Cache Yarn Dependencies"
description: "Get & Cache Yarn Dependencies"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
      # explicitly use node version 24
        node-version: 24
        cache: 'yarn'
        cache-dependency-path: 'ui/yarn.lock'
        # required for publishing
        registry-url: 'https://registry.npmjs.org'
    - name: Install Dependencies
      working-directory: ui
      run: yarn install --frozen-lockfile
      shell: bash