name: "Get & Cache Yarn Dependencies"
description: "Get & Cache Yarn Dependencies"
inputs:
  node-version:
    description: "Node version"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        cache: 'yarn'
        node-version: ${{ inputs.node-version }}
    - name: Install Dependencies
      working-directory: ui
      run: yarn install --frozen-lockfile
      shell: bash