name: "Get & Cache Yarn Dependencies"
description: "Get & Cache Yarn Dependencies"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        cache: 'yarn'
        cache-dependency-path: 'ui/yarn.lock'
        node-version-file: 'ui/package.json'
    - name: Install Dependencies
      working-directory: ui
      run: yarn install --frozen-lockfile
      shell: bash