---
name: Bug report
description: >-
  Report a bug or an unexpected behavior to help us improve UCC
title: 'BUG: '
labels:
- bug
- triage

body:
- type: markdown
  attributes:
    value: >
      ## Thank you for helping us improve UCC!

      * First, please verify that your issue is not already reported using the
      [Issue search](https://github.com/splunk/addonfactory-ucc-generator/search?q=is%3Aissue&type=issues).
- type: textarea
  attributes:
    label: Description
    description: A concise description of the bug.
  validations:
    required: true
- type: input
  attributes:
    label: What UCC version are you using?
    placeholder: For example splunk-add-on-ucc-framework==5.13.0
  validations:
    required: true
- type: input
  attributes:
    label: Additional System Info
    placeholder: Python version, OS (Linux/Mac/Windows/WSL), etc.
  validations:
    required: true
