---
name: Documentation update
description: Suggest a documentation update to improve everyone's experience
title: 'Docs: '
labels:
  - documentation
  - triage

body:
  - type: textarea
    id: search_area
    attributes:
      label: What were you searching in the docs?
      description: Please help us understand how you looked for information that was either unclear or not available
    validations:
      required: true
  - type: input
    id: area
    attributes:
      label: Is this related to an existing documentation section?
      description: Please share a link, if applicable
    validations:
      required: false
  - type: textarea
    id: idea
    attributes:
      label: How can we improve?
      description: Please share your thoughts on how we can improve this experience
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Got a suggestion in mind?
      description: Please suggest a proposed update
    validations:
      required: false
