# This script triggers tests on appropriate codeline (passed from command line)

function invoke_plan()
{
curl -X POST --user dzakharov:bamboo -d bamboo.variable.CODELINE=$CODELINE bamboo.variable.BRANCH=$BRANCH http://app-bamboo/rest/api/latest/queue/${1}?os_authType=basic
}


invoke_plan SOLUTIONSSA-SOLNSAAUDITANDDATAPROTECTIONFUNCTIONALBIEBER
invoke_plan SOLUTIONSSA-SOLNSAAUDITANDDATAPROTECTIONFUNCTIONALBIEBERLR
invoke_plan SOLUTIONSSA-SOLNSAAUDITANDDATAPROTECTIONFUNCTIONALCURRENT
invoke_plan SOLUTIONSSA-SOLNSAAUDITANDDATAPROTECTIONFUNCTIONALHAMMER
invoke_plan SOLUTIONSSA-SOLNSAAUDITANDDATAPROTECTIONFUNCTIONALHAMMERLR
