# This script triggers tests on appropriate codeline (passed from command line)

function invoke_plan()
{
curl -X POST --user dzakharov:bamboo -d bamboo.variable.CODELINE=$CODELINE  bamboo.variable.BRANCH=$BRANCH http://app-bamboo/rest/api/latest/queue/${1}?os_authType=basic
}

invoke_plan SOLUTIONSSA-SOLNSAUTILSUNITBIEBER
invoke_plan SOLUTIONSSA-SOLNSAUTILSUNITBIEBERLR
invoke_plan SOLUTIONSSA-SOLNSAUTILSUNITCURRENT
invoke_plan SOLUTIONSSA-SOLNSAUTILSUNITHAMMER
invoke_plan SOLUTIONSSA-SOLNSAUTILSUNITHAMMERLR

invoke_plan SOLUTIONSSA-SOLNSAUTILSFUNCTIONALBIEBER
invoke_plan SOLUTIONSSA-SOLNSAUTILSFUNCTIONALBIEBERLR
invoke_plan SOLUTIONSSA-SOLNSAUTILSFUNCTIONALCURRENT
invoke_plan SOLUTIONSSA-SOLNSAUTILSFUNCTIONALHAMMER
invoke_plan SOLUTIONSSA-SOLNSAUTILSFUNCTIONALHAMMERLR

invoke_plan SOLUTIONSSA-SOLNSAUTILSJSLINT
