# This script triggers tests on appropriate codeline (passed from command line)

function invoke_plan()
{
curl -X POST --user dzakharov:bamboo -d bamboo.variable.CODELINE=$CODELINE http://app-bamboo/rest/api/latest/queue/${1}?os_authType=basic
}

invoke_plan SOLUTIONSES-SOLNESFUNCTIONALBIEBER
#invoke_plan SOLUTIONSES-SOLNESFUNCTIONALACELR
#invoke_plan SOLUTIONSES-SOLNESFUNCTIONALCURRENT
invoke_plan SOLUTIONSES-SOLNESFUNCTIONALHAMMER
invoke_plan SOLUTIONSES-SOLNESFUNCTIONALHAMMERLR
invoke_plan SOLUTIONSES-SOLNESFUNCDISTNEXT

invoke_plan SOLUTIONSES-SOLNESFUNCTIONALRTBIEBER
#invoke_plan SOLUTIONSES-SOLNESFUNCTIONALRTBIEBERLR
#invoke_plan SOLUTIONSES-SOLNESFUNCTIONALRTCURRENT
invoke_plan SOLUTIONSES-SOLNESFUNCTIONALRTHAMMER
invoke_plan SOLUTIONSES-SOLNESFUNCTIONALRTHAMMERLR

invoke_plan SOLUTIONSES-SOLNESUNITBIEBER
invoke_plan SOLUTIONSES-SOLNESUNITBIEBERLR
invoke_plan SOLUTIONSES-SOLNESUNITCURRENT
invoke_plan SOLUTIONSES-SOLNESUNITHAMMER
invoke_plan SOLUTIONSES-SOLNESUNITHAMMERLR

invoke_plan SOLUTIONSES-SOLNESSMOKEBIEBER
invoke_plan SOLUTIONSES-SOLNESSMOKEBIEBERLR
invoke_plan SOLUTIONSES-ESSMOKECURRENT
invoke_plan SOLUTIONSES-ESSMOKEHAMMER
invoke_plan SOLUTIONSES-SOLNESSMOKEHAMMERLR

invoke_plan SOLUTIONSES-SOLNESJSLINT
