# This script triggers tests on appropriate codeline (passed from command line)

function invoke_plan()
{
curl -X POST --user dzakharov:bamboo -d bamboo.variable.CODELINE=$CODELINE  bamboo.variable.BRANCH=$BRANCH http://app-bamboo/rest/api/latest/queue/${1}?os_authType=basic
}

invoke_plan SOLUTIONSSA-SOLNSACOMMONINFORMATIONMODELFUNCTIONALBIEBER
invoke_plan SOLUTIONSSA-SOLNSACOMMONINFORMATIONMODELFUNCTIONALBIEBERLR
invoke_plan SOLUTIONSSA-SOLNSACOMMONINFORMATIONMODELFUNCTIONALCURRENT
invoke_plan SOLUTIONSSA-SOLNSACOMMONINFORMATIONMODELFUNCTIONALHAMMER
invoke_plan SOLUTIONSSA-SOLNSACOMMONINFORMATIONMODELFUNCTIONALHAMMERLR
