# This script triggers tests on appropriate codeline (passed from command line)

function invoke_plan()
{
curl -X POST --user dzakharov:bamboo -d bamboo.variable.CODELINE=$CODELINE http://app-bamboo/rest/api/latest/queue/${1}?os_authType=basic
}

invoke_plan SOLUTIONSPCI-SOLNPCIFUNCTIONALBIEBER
invoke_plan SOLUTIONSPCI-SOLNPCIFUNCTIONALBIEBERLR
invoke_plan SOLUTIONSPCI-SOLNPCIFUNCTIONALCURRENT

invoke_plan SOLUTIONSPCI-SOLNPCIFUNCTIONALRTBIEBER
invoke_plan SOLUTIONSPCI-SOLNPCIFUNCTIONALRTBIEBERLR
invoke_plan SOLUTIONSPCI-SOLNPCIFUNCTIONALRTCURRENT

invoke_plan SOLUTIONSPCI-SOLNPCISMOKEBIEBER
invoke_plan SOLUTIONSPCI-SOLNPCISMOKEBIEBERLR
invoke_plan SOLUTIONSPCI-SOLNPCISMOKECURRENT


invoke_plan SOLUTIONSPCI-SOLNPCIUNITBIEBER
invoke_plan SOLUTIONSPCI-SOLNPCIUNITBIEBERLR
invoke_plan SOLUTIONSPCI-SOLNPCIUNITCURRENT
