# This script triggers tests on appropriate codeline (passed from command line)

function invoke_plan()
{
curl -X POST --user dzakharov:bamboo -d bamboo.variable.CODELINE=$CODELINE  bamboo.variable.BRANCH=$BRANCH http://app-bamboo/rest/api/latest/queue/${1}?os_authType=basic
}

invoke_plan SOLUTIONSSA-SOLNSAIDENTITYMANAGEMENTUNITBIEBER
invoke_plan SOLUTIONSSA-SOLNSAIDENTITYMANAGEMENTUNITBIEBERLR
invoke_plan SOLUTIONSSA-SOLNSAIDENTITYMANAGEMENTUNITCURRENT
invoke_plan SOLUTIONSSA-SOLNSAIDENTITYMANAGEMENTUNITHAMMER
invoke_plan SOLUTIONSSA-SOLNESSIDENTITYMANAGEMENTHAMMERLR


invoke_plan SOLUTIONSSA-SOLNSAIDENTITYMANAGEMENTFUNCTIONALBIEBER
invoke_plan SOLUTIONSSA-SOLNSAIDENTITYMANAGEMENTFUNCTIONALBIEBERLR
invoke_plan SOLUTIONSSA-SOLNSAIDENTITYMANAGEMENTFUNCTIONALCURRENT
invoke_plan SOLUTIONSSA-SOLNSAIDENTITYMANAGEMENTFUNCTIONALHAMMER
invoke_plan SOLUTIONSSA-SOLNSAIDENTITYMANAGEMENTFUNCTIONALHAMMERLR

invoke_plan SOLUTIONSSA-SOLNSAIDENTITYMANAGEMENTJSLINT
