#
# Copyright 2025 Splunk Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""
Reverse engineer a UCC project from a built add-on package.

This command extracts the source structure from a built add-on,
allowing you to modify and rebuild it.
"""
import configparser
import glob
import json
import logging
import os
import shutil
import sys
import tarfile
import tempfile
from typing import Optional

logger = logging.getLogger("ucc_gen")


# Files/directories that are generated by UCC and should not be copied to package/
GENERATED_PATTERNS = [
    "bin/*_rh_*.py",  # REST handlers
    "bin/*_input.py",  # Modular input wrappers (not helpers)
    "default/data/ui/views/configuration.xml",  # Generated UI views
    "default/data/ui/views/inputs.xml",
    "default/data/ui/views/dashboard.xml",
    "default/data/ui/nav/default.xml",  # May be partially generated
    "appserver/static/js/build/entry_page.js",  # Built UI
    "appserver/static/js/build/*.js",  # All built JS
    "appserver/static/js/build/*.css",  # Built CSS
    "appserver/static/openapi.json",  # Generated OpenAPI spec
]


def reverse(
    addon_path: str,
    output_directory: Optional[str] = None,
    overwrite: bool = False,
) -> None:
    """
    Reverse engineer a UCC project from a built add-on package.

    Args:
        addon_path: Path to the built add-on directory or .tar.gz package
        output_directory: Path where the project should be created
        overwrite: Whether to overwrite existing output directory
    """
    logger.info(f"ucc-gen reverse: Extracting project from {addon_path}")

    # Check if it's a tarball or directory
    cleanup_temp = False
    temp_dir = None
    
    if os.path.isfile(addon_path) and addon_path.endswith(('.tar.gz', '.tgz', '.spl')):
        # It's a tarball - extract it first
        logger.info("Detected package file, extracting...")
        temp_dir = tempfile.mkdtemp(prefix="ucc_reverse_")
        cleanup_temp = True
        
        try:
            with tarfile.open(addon_path, 'r:gz') as tar:
                tar.extractall(path=temp_dir)
            
            # Find the add-on directory inside
            extracted_items = os.listdir(temp_dir)
            if len(extracted_items) == 1 and os.path.isdir(os.path.join(temp_dir, extracted_items[0])):
                addon_path = os.path.join(temp_dir, extracted_items[0])
            else:
                addon_path = temp_dir
            
            logger.info("  ✓ Extracted to temporary directory")
        except Exception as e:
            logger.error(f"Failed to extract tarball: {e}")
            if cleanup_temp and temp_dir:
                shutil.rmtree(temp_dir, ignore_errors=True)
            sys.exit(1)
    elif not os.path.isdir(addon_path):
        logger.error(
            f"Add-on path '{addon_path}' does not exist or is not a directory/package file.\n"
            "Supported formats: directory, .tar.gz, .tgz, .spl"
        )
        sys.exit(1)

    addon_name = os.path.basename(os.path.normpath(addon_path))
    
    # Determine output directory
    if output_directory is None:
        output_directory = os.path.join(os.getcwd(), f"{addon_name}_source")
    
    output_directory = os.path.abspath(output_directory)
    
    # Check if output exists
    if os.path.exists(output_directory):
        if not overwrite:
            logger.error(
                f"Output directory '{output_directory}' already exists. "
                "Use --overwrite to overwrite it."
            )
            sys.exit(1)
        else:
            logger.info(f"Removing existing directory: {output_directory}")
            shutil.rmtree(output_directory)
    
    # Create output structure
    os.makedirs(output_directory, exist_ok=True)
    package_dir = os.path.join(output_directory, "package")
    os.makedirs(package_dir, exist_ok=True)

    logger.info(f"Creating project structure in: {output_directory}")

    # Step 1: Extract globalConfig.json
    _extract_global_config(addon_path, output_directory)

    # Step 2: Copy app.manifest (to root, not package/)
    _copy_app_manifest(addon_path, output_directory)

    # Step 3: Copy source files (excluding generated ones)
    _copy_source_files(addon_path, package_dir)

    # Step 4: Extract requirements.txt from lib/
    _extract_requirements(addon_path, package_dir)

    # Step 5: Create README
    _create_readme(output_directory, addon_name)

    logger.info("=" * 70)
    logger.info("✅ Project successfully extracted!")
    logger.info(f"📁 Location: {output_directory}")
    logger.info("")
    logger.info("📋 Next steps:")
    logger.info(f"   cd {output_directory}")
    logger.info("   # Make your modifications")
    logger.info("   ucc-gen build")
    logger.info("=" * 70)
    
    # Cleanup temp directory if we extracted a tarball
    if cleanup_temp and temp_dir:
        shutil.rmtree(temp_dir, ignore_errors=True)


def _extract_global_config(addon_path: str, output_dir: str) -> None:
    """Extract globalConfig.json or globalConfig.yaml from the built add-on."""
    logger.info("Extracting globalConfig...")
    
    build_dir = os.path.join(addon_path, "appserver", "static", "js", "build")
    
    for config_name in ["globalConfig.json", "globalConfig.yaml"]:
        config_path = os.path.join(build_dir, config_name)
        if os.path.exists(config_path):
            dest_path = os.path.join(output_dir, config_name)
            shutil.copy2(config_path, dest_path)
            logger.info(f"  ✓ Extracted {config_name}")
            return
    
    logger.warning("  ⚠ globalConfig file not found in add-on")


def _copy_app_manifest(addon_path: str, output_dir: str) -> None:
    """Copy app.manifest to output directory (project root), or create a minimal one."""
    logger.info("Copying app.manifest...")
    
    manifest_path = os.path.join(addon_path, "app.manifest")
    dest_path = os.path.join(output_dir, "app.manifest")
    
    if os.path.exists(manifest_path):
        shutil.copy2(manifest_path, dest_path)
        logger.info("  ✓ Copied app.manifest")
    else:
        logger.warning("  ⚠ app.manifest not found, creating minimal version")
        # Extract add-on name from path
        addon_name = os.path.basename(os.path.normpath(addon_path))
        
        # Try to read app.conf for metadata
        app_conf_path = os.path.join(addon_path, "default", "app.conf")
        version = "1.0.0"
        
        if os.path.exists(app_conf_path):
            try:
                import configparser
                config = configparser.ConfigParser()
                config.read(app_conf_path)
                if config.has_section("launcher") and config.has_option("launcher", "version"):
                    version = config.get("launcher", "version")
            except Exception as e:
                logger.debug(f"Could not read version from app.conf: {e}")
        
        # Create minimal manifest
        manifest_content = {
            "schemaVersion": "2.0.0",
            "info": {
                "title": addon_name,
                "id": {
                    "group": None,
                    "name": addon_name,
                    "version": version
                },
                "author": [
                    {
                        "name": "Unknown",
                        "email": None,
                        "company": None
                    }
                ],
                "releaseDate": None,
                "description": f"Reverse-engineered from {addon_name}",
                "classification": {
                    "intendedAudience": None,
                    "categories": [],
                    "developmentStatus": None
                },
                "commonInformationModels": None,
                "license": {
                    "name": None,
                    "text": None,
                    "uri": None
                },
                "privacyPolicy": {
                    "name": None,
                    "text": None,
                    "uri": None
                },
                "releaseNotes": {
                    "name": None,
                    "text": None,
                    "uri": None
                }
            },
            "dependencies": None,
            "tasks": None,
            "inputGroups": None,
            "incompatibleApps": None,
            "platformRequirements": None,
            "supportedDeployments": ["*"],
            "targetWorkloads": ["*"]
        }
        
        import json
        with open(dest_path, 'w') as f:
            json.dump(manifest_content, f, indent=2)
        
        logger.info("  ✓ Created minimal app.manifest")


def _copy_source_files(addon_path: str, package_dir: str) -> None:
    """
    Copy source files from add-on to package, excluding generated files.
    """
    logger.info("Copying source files...")
    
    copied_count = 0
    skipped_count = 0
    
    for root, dirs, files in os.walk(addon_path):
        # Skip certain directories entirely
        rel_root = os.path.relpath(root, addon_path)
        
        # Skip the build directory (except globalConfig which we already extracted)
        if "appserver/static/js/build" in rel_root:
            continue
        
        # Skip lib directory (we'll regenerate requirements.txt)
        if rel_root.startswith("lib"):
            continue
        
        for file in files:
            src_file = os.path.join(root, file)
            rel_file = os.path.relpath(src_file, addon_path)
            
            # Check if file matches any generated pattern
            if _is_generated_file(rel_file):
                skipped_count += 1
                logger.debug(f"  - Skipping generated: {rel_file}")
                continue
            
            # Copy the file
            dest_file = os.path.join(package_dir, rel_file)
            os.makedirs(os.path.dirname(dest_file), exist_ok=True)
            shutil.copy2(src_file, dest_file)
            copied_count += 1
    
    logger.info(f"  ✓ Copied {copied_count} source files")
    logger.info(f"  ℹ Skipped {skipped_count} generated files")


def _is_generated_file(filepath: str) -> bool:
    """Check if a file matches generated patterns."""
    import fnmatch
    
    for pattern in GENERATED_PATTERNS:
        if fnmatch.fnmatch(filepath, pattern):
            return True
    return False


def _extract_requirements(addon_path: str, package_dir: str) -> None:
    """
    Extract requirements.txt from installed packages in lib/.
    """
    logger.info("Extracting requirements.txt from lib/...")
    
    lib_path = os.path.join(addon_path, "lib")
    if not os.path.isdir(lib_path):
        logger.warning("  ⚠ No lib/ directory found")
        return
    
    packages = {}
    
    # Find all .dist-info directories
    dist_info_pattern = os.path.join(lib_path, "**", "*.dist-info")
    for dist_info_path in glob.glob(dist_info_pattern, recursive=True):
        metadata_file = os.path.join(dist_info_path, "METADATA")
        
        if not os.path.exists(metadata_file):
            metadata_file = os.path.join(dist_info_path, "PKG-INFO")
        
        if os.path.exists(metadata_file):
            try:
                name, version = _parse_package_metadata(metadata_file)
                if name and version:
                    packages[name.lower()] = version
            except Exception as e:
                logger.debug(f"  - Could not parse {metadata_file}: {e}")
    
    if not packages:
        logger.warning("  ⚠ No packages found in lib/")
        return
    
    # Create lib directory and requirements.txt
    lib_dir = os.path.join(package_dir, "lib")
    os.makedirs(lib_dir, exist_ok=True)
    
    requirements_path = os.path.join(lib_dir, "requirements.txt")
    with open(requirements_path, 'w') as f:
        f.write("# Auto-generated from built add-on's lib/ directory\n")
        f.write("# This will reproduce the exact package versions\n")
        f.write("# You may want to adjust version constraints (== to >=)\n")
        f.write("\n")
        
        for pkg_name in sorted(packages.keys()):
            version = packages[pkg_name]
            f.write(f"{pkg_name}=={version}\n")
    
    logger.info(f"  ✓ Created requirements.txt with {len(packages)} packages")


def _parse_package_metadata(metadata_file: str) -> tuple[Optional[str], Optional[str]]:
    """Parse Name and Version from METADATA or PKG-INFO file."""
    name = None
    version = None
    
    with open(metadata_file, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            line = line.strip()
            
            if line.startswith("Name:"):
                name = line.split(":", 1)[1].strip()
            elif line.startswith("Version:"):
                version = line.split(":", 1)[1].strip()
            
            if name and version:
                break
    
    return name, version


def _create_readme(output_dir: str, addon_name: str) -> None:
    """Create a README explaining what was extracted and limitations."""
    logger.info("Creating README...")
    
    readme_content = f"""# {addon_name} - Extracted Source Project

This project was reverse-engineered from a built UCC add-on package using `ucc-gen reverse`.

## ⚠️ Important Notes

This extracted project is **functional but may have limitations**:

### ✅ What was successfully extracted:
- `globalConfig.json` - Complete configuration
- `app.manifest` - Add-on metadata
- Source files from `package/` (`.conf`, `.py`, static assets)
- `lib/requirements.txt` - Recreated with exact package versions

### ⚠️ What may be missing or incomplete:
- **Custom UI components** (TypeScript/React) - These were bundled and cannot be recovered
  - If the original had custom UI, placeholder stubs would need to be created
- **Build scripts** - Custom build automation scripts
- **Development tooling** - `.gitignore`, dev dependencies, etc.

### 📦 Requirements.txt Note
The `lib/requirements.txt` file was generated with **pinned versions** (`==`) to ensure
identical package installations. You may want to:
- Review and adjust version constraints to use `>=` for more flexibility
- Remove unnecessary transitive dependencies if you know the top-level requirements

## 🚀 How to Use This Project

1. **Review the extracted files**:
   ```bash
   cd {addon_name}_source
   ```

2. **Make your modifications**:
   - Edit `globalConfig.json` for configuration changes
   - Modify Python helpers in `package/bin/`
   - Update `.conf` files as needed

3. **Build the add-on**:
   ```bash
   ucc-gen build
   ```

4. **The built add-on will be in**:
   ```
   output/{addon_name}/
   ```

## 📖 Documentation

For more information about UCC framework:
- [UCC Documentation](https://splunk.github.io/addonfactory-ucc-generator/)
- [GlobalConfig Schema](https://splunk.github.io/addonfactory-ucc-generator/entity/)

---

**Generated by**: `ucc-gen reverse`  
**Extraction Date**: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
    
    readme_path = os.path.join(output_dir, "README.md")
    with open(readme_path, 'w') as f:
        f.write(readme_content)
    
    logger.info("  ✓ Created README.md")
