name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  call-workflow-agreements:
    uses: splunk/addonfactory-github-workflows/.github/workflows/reusable-agreements.yaml@v1.2.1
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_CLATOOL }}
