name: "Build Storybook"
on:
  workflow_call:

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: install deps
        uses: ./.github/actions/cached-ui-deps
        with:
          node-version: ${{ inputs.node-version }}
      - name: Build UCC UI
        run: yarn run build-storybook
      - name: Upload dist with name UCC-UI-build
        uses: actions/upload-artifact@v3
        with:
          name: UCC-UI-storybook
          path: ui/storybook-static