name: TAs Regression Test

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      target_repo:
        description: "Target repository"
        required: false
        default: ""
      target_branch:
        description: "Target branch"
        required: false
        default: "main"

jobs:
  build-ucc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout UCC Framework Repository
        uses: actions/checkout@v4
        with:
          path: UCC

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"

      - name: Install Poetry
        run: pip install poetry==1.5.1

      - name: Build UCC Framework Package
        working-directory: UCC
        run: |
          poetry install
          poetry build

      - name: Upload UCC Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ucc-package-whl
          path: UCC/dist/*.whl

  determine-repos:
    runs-on: ubuntu-22.04
    outputs:
      repos: ${{ steps.set-repos.outputs.repos }}
    steps:
      - id: set-repos
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.target_repo }}" != "" ]]; then
            echo "repos=[\"${{ github.event.inputs.target_repo }}\"]" >> $GITHUB_OUTPUT
          else
            echo 'repos=[
              "splunk/splunk-add-on-for-amazon-web-services",
              "splunk/splunk-add-on-for-google-cloud-platform",
              "splunk/splunk-add-on-for-google-workspace",
              "splunk/splunk-add-on-for-microsoft-cloud-services",
              "splunk/splunk-add-on-for-microsoft-office-365",
              "splunk/splunk-add-on-for-salesforce",
              "splunk/splunk-add-on-for-servicenow",
              "splunk/splunk-add-on-for-mysql"
            ]' >> $GITHUB_OUTPUT
          fi

  test-addons:
    needs: [ build-ucc, determine-repos ]
    strategy:
      matrix:
        target_repo: ${{ fromJSON(needs.determine-repos.outputs.repos) }}
    continue-on-error: true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Target Add-on Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.target_repo }}
          path: TA
          token: ${{ secrets.GH_TOKEN_ADMIN }}
          ref: ${{ github.event.inputs.target_branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"

      - name: Install Poetry
        run: pip install poetry==1.5.1

      - name: Download UCC Artifact
        uses: actions/download-artifact@v4
        with:
          name: ucc-package-whl
          path: UCC

      - name: Install Dependencies in Target Add-on
        working-directory: TA
        run: |
          UCC_WHL=$(ls ../UCC/*.whl)
          # https://github.com/python-poetry/poetry/issues/7491#issuecomment-1423763839
          git config --global --add url."https://${{ secrets.GH_TOKEN_ADMIN }}@github.com".insteadOf https://github.com
          git config --global --add url."https://${{ secrets.GH_TOKEN_ADMIN }}@github.com".insteadOf ssh://git@github.com
          poetry add ../UCC/$UCC_WHL --group dev
          poetry add splunktaucclib@latest
          mkdir -p package/lib
          poetry export --without-hashes -o package/lib/requirements.txt

      - name: Run ucc-gen build in Target Add-on
        working-directory: TA
        run: |
          poetry run ucc-gen build

      - name: Run TA Unit Tests
        # run only if pytest-ci.ini exists in the unit test directory
        if: ${{ hashFiles('TA/tests/unit/pytest-ci.ini') != '' }}
        working-directory: TA
        run: |
          # prevents "pytest_plugins in non-top-level conftest files" error 
          cp tests/unit/pytest-ci.ini pytest.ini
          poetry run pytest --junitxml=test-results/junit.xml tests/unit